name: Cache Blogger Posts

on:
  schedule:
    - cron: "0 3 * * *" # todos los días a las 03:00 UTC
  workflow_dispatch: # para lanzarlo manualmente también

jobs:
  fetch-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch Blogger posts
        run: node scripts/fetch-posts.js
        env:
          BLOGGER_API_KEY: ${{ secrets.BLOGGER_API_KEY }}
          BLOGGER_BLOG_ID: ${{ vars.BLOGGER_BLOG_ID }}

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/blog-posts.json
          git commit -m "chore: update blogger cache [skip ci]" || echo "No changes to commit"
          git push
